const dummyIdeas = [
    {
        id:1, 
        ideaName: 'build an ecommerce website',
        claimed: false,
        email: 'name1@email.com',
        submitted: false,
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
        authorName: 'Name 1'
    },
    {
        id:2, 
        ideaName: 'develop a singles matching app', 
        authorName: 'Name 2',
        email: 'name2@email.com',
        submitted: false,
        claimed: true, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium'
    },
    {
        id:3, 
        ideaName: 'come up with an algorithm to calculate something', 
        email: 'name3@email.com',
        authorName: 'Name 3',
        claimed: false, 
        submitted: false,
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:4, 
        ideaName: 'build a database of stuff', 
        email: 'name4@email.com',
        authorName: 'Name 4',
        submitted: false,
        claimed: true, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:5, 
        authorName: 'Name 5',
        email: 'name5@email.com',
        ideaName: 'collaborate on a join project',
        submitted: false, 
        claimed: false, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:6, 
        authorName: 'Name 6',
        email: 'name6@email.com',
        ideaName: 'put my portfolio on line', 
        submitted: false,
        claimed: true, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium'
    },
    {
        id:7, 
        authorName: 'Name 7',
        email: 'name7@email.com',
        ideaName: 'set up a gofundme account', 
        submitted: false,
        claimed: false, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:8,
        authorName: 'Name 8', 
        email: 'name8@email.com',
        ideaName: 'create a chess game', 
        submitted: false,
        claimed: true, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:9, 
        ideaName: 'add AI to my current app', 
        email: 'name9@email.com',
        authorName: 'Name 9',
        submitted: false,
        claimed: false, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },
    {
        id:10, 
        ideaName: 'build a front end for my server',
        email: 'name10@email.com',
        authorName: 'Name 10',
        submitted: false,
        claimed: true, 
        ideaSummary:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    },

]

export default dummyIdeas